feat: New options and defaults
Added:
- Option --exclude-content — to specify tables with ignored content
- More new options --quiet, --bzip2 and --help

BREAKING CHANGE:
- Default behaviour: write in stdout, don't compress by bzip2, don't use password

diff --git a/bin/mysqltwindump b/bin/mysqltwindump
--- a/bin/mysqltwindump
+++ b/bin/mysqltwindump
@@ -3,98 +3,149 @@
 set -eo pipefail
 
 # Initialize variables:
-PROG_NAME="mysqltwindump"
 DB_HOST="localhost"
 DB_PORT="3306"
 DB_USER=""
 DB_PASSWORD=""
 DB_NAME=""
-DUMP_FILENAME="dump_$(date +%Y-%m-%d_%H-%M).sql.bz2"
-DRY_RUN=false
-
-EXCLUDE_TABLES="b_event_log
-b_event
-b_perf_sql"
-
-EXCLUDE_TABLES_INLINE=""
-for TABLE in $EXCLUDE_TABLES
-do
-    EXCLUDE_TABLES_INLINE="${EXCLUDE_TABLES_INLINE} ${TABLE}"
-done
-
+OUTPUT_FILENAME=""
+DRY_RUN=""
+BZIP=""
+QUIET=""
+USE_PASSWORD=""
+declare -a EXCLUDE_CONTENT_TABLES
 MYSQL_DUMP_COMMON_OPTIONS="--single-transaction --quick --add-drop-table --skip-lock-tables --set-gtid-purged=OFF"
 
-getopt --options "h::P::u:p:d:o:" \
-       --longoptions "host::,port::,user:,password:,database:,output::,dry-run" \
-       --name "${PROG_NAME}" \
+function displayUsage() {
+  printf "\nNAME\n" >&2
+  printf "\t%s - Dumps an entire MySQL database to a single *.sql or *.sql.bz2 file, ignoring contents for specific set of tables. \n" "$0" >&2
+  printf "\nSYNOPSIS\n" >&2
+  printf "\t%s %%options%%\n" "$0" >&2
+  printf "\nOPTIONS\n" >&2
+  printf "\t-e, --exclude-content \"table1[ table2 table3...]\"\n" >&2
+  printf "\t\tTables with ignored content. Required.\n\n" >&2
+  printf "\t-d, --database %%database%%\n" >&2
+  printf "\t\tDatabase name. Required.\n\n" >&2
+  printf "\t-u, --user %%user%%\n" >&2
+  printf "\t\tDatabase user name. Required.\n\n" >&2
+  printf "\t-p, --password %%password%%\n" >&2
+  printf "\t\tUser password. Default: don't send password. " >&2
+  printf "If empty line, the password will be asked by mysqldump. " >&2
+  printf "The password must be in quotes, if it has spaces.\n\n" >&2
+  printf "\t-h, --host \"%s\"\n" "${DB_HOST}" >&2
+  printf "\t\tDatabase host.\n\n" >&2
+  printf "\t-P, --port %s\n" "${DB_PORT}" >&2
+  printf "\t\tDatabase port.\n\n" >&2
+  printf "\t-o, --output %%filepath%%\n" >&2
+  printf "\t\tDump filename to write to. Default: stdout\n\n" >&2
+  printf "\t-b, --bzip2\n" >&2
+  printf "\t\tUse bzip2 compression. Default: don't compress.\n\n" >&2
+  printf "\t--dry-run\n" >&2
+  printf "\t\tDon't do anything for real. Just print out commands that would be used in normal operation mode.\n\n" >&2
+  printf "\t-q, --quiet\n" >&2
+  printf "\t\tSuppress any output. Default: print current status.\n\n" >&2
+  printf "\t--help\n" >&2
+  printf "\t\tDisplay this help message.\n\n" >&2
+  exit
+}
+
+getopt --options "h::P::u:p::d:e:bqo:" \
+       --longoptions "host::,port::,user:,password:,database:,exclude-content,bzip2,quiet,output,dry-run,help" \
+       --name "$0" \
        -- "$@" > /dev/null
 
-# shellcheck disable=SC2181
-if [ $? -ne 0 ]; then
-  printf "\nNAME:\n" >&2
-  printf "\t%s - Dump Bitrix database\n" $PROG_NAME >&2
-  printf "\nSYNOPSIS:\n" >&2
-  printf "\t%s options\n" $PROG_NAME >&2
-  printf "\nOPTIONS:\n" >&2
-  printf "\t-h, --host\n" >&2
-  printf "\t\tDatabase host\n\n" >&2
-  printf "\t-P, --port\n" >&2
-  printf "\t\tDatabase port\n\n" >&2
-  printf "\t-u, --user\n" >&2
-  printf "\t\tDatabase user name\n\n" >&2
-  printf "\t-p, --password\n" >&2
-  printf "\t\tUser password\n\n" >&2
-  printf "\t-d, --database\n" >&2
-  printf "\t\tDatabase name\n\n" >&2
-  printf "\t-o, --output\n" >&2
-  printf "\t\tOutput *.sql.bz2 file name\n\n" >&2
-  exit $?
-fi
-
-while true; do
+while true ; do
   case "$1" in
     -h | --host ) DB_HOST="$2"; shift 2 ;;
     -P | --port ) DB_PORT="$2"; shift 2 ;;
     -u | --user ) DB_USER="$2"; shift 2 ;;
-    -p | --password ) DB_PASSWORD="$2"; shift 2 ;;
+    -p | --password ) DB_PASSWORD="$2"; USE_PASSWORD=true ; shift 2 ;;
     -d | --database ) DB_NAME="$2"; shift 2 ;;
-    -o | --output ) DUMP_FILENAME="$2"; shift 2 ;;
+    -e | --exclude-content )
+      # We need array in here.
+      # shellcheck disable=SC2206
+      EXCLUDE_CONTENT_TABLES=($2); shift 2 ;;
+    -b | --bzip2 ) BZIP=true; shift ;;
+    -q | --quiet ) QUIET=true; shift ;;
+    -o | --output ) OUTPUT_FILENAME="$2"; shift 2 ;;
     --dry-run ) DRY_RUN=true; shift ;;
+    --help ) displayUsage ;;
     * ) break ;;
   esac
 done
 
-if [ -z "${DUMP_FILENAME}" ]; then
-  DUMP_FILENAME="${DB_NAME}_$(date +%Y-%m-%d_%H-%M).sql.bz2"
+if [[ -z "${EXCLUDE_CONTENT_TABLES[*]}" ]]; then
+  echo "Missing tables with excluded content" >&2
+  displayUsage
+fi
+if [[ -z "${DB_USER}" ]]; then
+  echo "Missing user" >&2
+  displayUsage
+fi
+if [[ -z "${DB_NAME}" ]]; then
+  echo "Missing database" >&2
+  displayUsage
 fi
 
-#TODO Добавить запись инструкции на удаление всех таблиц в БД перед началом.
-#TODO Сделать динамическую сборку аргументов `--ignore-table`
 
-echo "Dump ${DB_NAME}@${DB_HOST}:${DB_PORT} to ${DUMP_FILENAME}"
-echo "Packing tables with data, excluding ${EXCLUDE_TABLES_INLINE} tables..."
-# shellcheck disable=SC2086
-if ! $DRY_RUN; then
-  mysqldump $MYSQL_DUMP_COMMON_OPTIONS \
-            --ignore-table="${DB_NAME}.b_event_log" \
-            --ignore-table="${DB_NAME}.b_event" \
-            --ignore-table="${DB_NAME}.b_perf_sql" \
-            --ignore-table="${DB_NAME}.b_sms4b"  \
-            -h "${DB_HOST}" \
-            -P "${DB_PORT}" \
-            -u "${DB_USER}" \
-            -p"${DB_PASSWORD}" \
-            "${DB_NAME}" | bzip2 -c > "${DUMP_FILENAME}"
+# TODO Добавить запись инструкции на удаление всех таблиц в БД перед началом.
+#      И такую инструкцию можно добавлять по желанию
+
+if [[ $USE_PASSWORD ]]; then
+  PASSWORD_OPTION="-p\"${DB_PASSWORD}\""
+else
+  PASSWORD_OPTION=""
 fi
-echo "Packing table structure for ${EXCLUDE_TABLES_INLINE} tables..."
-# shellcheck disable=SC2086
-if ! $DRY_RUN; then
-  mysqldump $MYSQL_DUMP_COMMON_OPTIONS \
-            -h "${DB_HOST}" \
-            -P "${DB_PORT}" \
-            -u "${DB_USER}" \
-            -p"${DB_PASSWORD}" \
-            "${DB_NAME}" \
-            $EXCLUDE_TABLES_INLINE | bzip2 -c >> "${DUMP_FILENAME}"
-  du -sh "${DUMP_FILENAME}"
+ACCESS_OPTIONS="-h \"${DB_HOST}\" \
+                -P \"${DB_PORT}\" \
+                -u \"${DB_USER}\" \
+                ${PASSWORD_OPTION} \
+                \"${DB_NAME}\""
+
+IGNORE_TABLE_OPTIONS=""
+for TABLE in ${EXCLUDE_CONTENT_TABLES[*]} ; do
+    IGNORE_TABLE_OPTIONS="$IGNORE_TABLE_OPTIONS --ignore-table=\"${DB_NAME}.${TABLE}\""
+done
+
+if [[ ! "$QUIET" ]]; then
+  echo "Dumping ${DB_NAME}@${DB_HOST}:${DB_PORT}" >&2
+  echo "Packing tables with data, excluding ${EXCLUDE_CONTENT_TABLES[*]} ..." >&2
+fi
+COMMAND="mysqldump $MYSQL_DUMP_COMMON_OPTIONS \
+                   $ACCESS_OPTIONS \
+                   $IGNORE_TABLE_OPTIONS"
+if [[ "$BZIP" ]]; then
+  COMMAND="$COMMAND | bzip2 -c"
+fi
+if [[ -n "${OUTPUT_FILENAME}" ]]; then
+  COMMAND="$COMMAND > $OUTPUT_FILENAME"
+fi
+if [[ $DRY_RUN ]]; then
+  echo "$COMMAND" >&2
+else
+  # shellcheck disable=SC2086
+  eval $COMMAND
+fi
+
+if [[ ! "$QUIET" ]]; then
+  echo "Packing table structure for ${EXCLUDE_CONTENT_TABLES[*]} ..." >&2
+fi
+COMMAND="mysqldump $MYSQL_DUMP_COMMON_OPTIONS \
+                   $ACCESS_OPTIONS \
+                   --no-data \
+                   ${EXCLUDE_CONTENT_TABLES[*]}"
+if [[ "$BZIP" ]]; then
+  COMMAND="$COMMAND | bzip2 -c"
+fi
+if [[ -n "${OUTPUT_FILENAME}" ]]; then
+  COMMAND="$COMMAND >> $OUTPUT_FILENAME"
+fi
+if [[ $DRY_RUN ]]; then
+  echo "$COMMAND" >&2
+else
+  # shellcheck disable=SC2086
+  eval $COMMAND
+fi
+if [[ ! "$QUIET" ]]; then
+  echo "Done." >&2
 fi
